import { Category } from './types';

export const WIZARD_CATEGORIES: Category[] = [
  { id: 'web', title: 'Web Development', blurb: 'Websites, SaaS apps' },
  { id: 'mobile', title: 'Mobile App Development', blurb: 'Android / iOS apps' },
  { id: 'game', title: 'Game Development', blurb: 'PC, mobile & console games' },
  { id: 'ai', title: 'AI & Machine Learning', blurb: 'AI systems & models' },
  { id: 'security', title: 'Cybersecurity', blurb: 'Security tools, ethical hacking' },
  { id: 'cloud', title: 'Cloud Computing', blurb: 'Cloud infrastructure & services' },
  { id: 'devops', title: 'DevOps', blurb: 'Deployment automation' },
  { id: 'data', title: 'Data Science', blurb: 'Data analysis systems' },
  { id: 'web3', title: 'Blockchain / Web3', blurb: 'Decentralized apps' },
  { id: 'embedded', title: 'Embedded Systems', blurb: 'Hardware-integrated software' },
  { id: 'arvr', title: 'AR / VR Development', blurb: 'Virtual & augmented reality' },
  { id: 'film', title: 'Filmmaking', blurb: 'Film & episodic storytelling' },
  { id: 'music', title: 'Music', blurb: 'Recording & composition' },
  { id: 'writing', title: 'Writing', blurb: 'Scripts & long-form work' },
  { id: 'design', title: 'Design', blurb: 'Visual & product design' },
  { id: 'content', title: 'Content Creation', blurb: 'Creator-led media' },
  { id: 'photography', title: 'Photography', blurb: 'Photo & editorial' },
  { id: 'animation', title: 'Animation', blurb: '2D/3D & motion' },
  { id: 'marketing', title: 'Marketing', blurb: 'Growth & brand' },
  { id: 'education', title: 'Education', blurb: 'Learning products' },
  { id: 'health', title: 'Health & Wellness', blurb: 'Fitness & wellbeing' },
];

export const WIZARD_SKILLS_MAP: Record<string, string[]> = {
  web: [
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'UI/UX Designer',
    'Solutions Architect',
  ],
  mobile: [
    'iOS Developer',
    'Android Developer',
    'React Native Developer',
    'Mobile UI Designer',
    'QA Mobile',
  ],
  game: [
    'Game Designer',
    'Unity / Unreal Developer',
    '3D Artist',
    'Level Designer',
    'Technical Artist',
    'Console / PC Programmer',
  ],
  ai: [
    'ML Engineer',
    'AI Researcher',
    'MLOps Engineer',
    'Data Engineer',
    'LLM Application Developer',
  ],
  security: [
    'Security Engineer',
    'Penetration Tester',
    'SOC Analyst',
    'Security Architect',
    'GRC Specialist',
  ],
  cloud: [
    'Cloud Architect',
    'AWS / Azure / GCP Engineer',
    'Site Reliability Engineer',
    'Solutions Engineer',
    'FinOps Analyst',
  ],
  devops: [
    'DevOps Engineer',
    'CI/CD Specialist',
    'Platform Engineer',
    'Infrastructure as Code',
    'Release Manager',
  ],
  data: [
    'Data Scientist',
    'Data Analyst',
    'BI Developer',
    'Quantitative Analyst',
    'Visualization Specialist',
  ],
  web3: [
    'Smart Contract Developer',
    'Blockchain Engineer',
    'dApp Frontend Developer',
    'Web3 Product Designer',
    'Tokenomics Consultant',
  ],
  embedded: [
    'Embedded Software Engineer',
    'Firmware Developer',
    'IoT Engineer',
    'Hardware-Software Integration',
    'RTOS Specialist',
  ],
  arvr: [
    'AR / VR Engineer',
    'Unity / Unreal XR Developer',
    '3D Environment Artist',
    'XR Interaction Designer',
    'Technical Artist XR',
  ],
  film: ['Director', 'Editor', 'Cinematographer', 'Writer', 'Actor', 'Music Composer'],
  music: ['Singer', 'Producer', 'Lyricist', 'Guitarist'],
  writing: ['Story Writer', 'Script Writer', 'Editor', 'Poet'],
  design: ['Graphic Designer', 'Product Designer', 'Illustrator', 'Motion Designer'],
  content: ['Video Creator', 'Editor', 'Thumbnail Designer', 'Social Media Manager'],
  photography: [
    'Photographer',
    'Photo Editor',
    'Portrait Specialist',
    'Event Photographer',
    'Product Photographer',
  ],
  animation: [
    '2D Animator',
    '3D Animator',
    'Motion Graphics Artist',
    'Character Designer',
    'Storyboard Artist',
  ],
  marketing: [
    'Digital Marketer',
    'SEO Specialist',
    'Social Media Strategist',
    'Content Marketer',
    'Brand Manager',
  ],
  education: [
    'Educator',
    'Curriculum Developer',
    'E-Learning Specialist',
    'Trainer',
    'Educational Content Creator',
  ],
  health: [
    'Fitness Trainer',
    'Nutritionist',
    'Mental Health Coach',
    'Wellness Consultant',
    'Health Content Creator',
  ],
};

export const WIZARD_COPY = [
  { title: 'Choose your path', subtitle: 'Select how you want to begin.' },
  { title: 'Select category', subtitle: 'Pick one world you want to build in.' },
  { title: 'Select skills', subtitle: 'Choose all skills needed for your project.' },
  { title: 'Project details', subtitle: 'Add the essentials your team needs.' },
  { title: 'Project motive', subtitle: 'Share the vision that inspires your team.' },
  { title: 'Budget & compensation', subtitle: 'Set the salary range for your team.' },
  { title: 'Launch ready', subtitle: 'Your creator journey is now unlocked.' },
];

export const QUOTES = [
  'Big projects begin with one bold decision.',
  'A clear vision attracts the right creators.',
  'Collaboration turns ideas into movements.',
];

export const JOIN_QUOTES = [
  'Great teams are built by people who show up with purpose.',
  'Your skills can unlock someone else\'s big vision.',
  'The right project can change your creative journey.',
];

export const SPLASH_DURATION_MS = 2400;

export const MOCK_INVITE_CREATORS = [
  {
    id: 'p1',
    name: 'Arjun Patel',
    tagline: 'Full-stack developer, 8 years experience',
    skills: ['Frontend Developer', 'Backend Developer', 'Full Stack Developer'],
    rateMin: 4000,
    rateMax: 12000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['web', 'mobile'],
  },
  {
    id: 'p2',
    name: 'Maya Chen',
    tagline: 'UI/UX Designer, passionate about user experience',
    skills: ['UI/UX Designer', 'Product Designer'],
    rateMin: 3500,
    rateMax: 10000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['web', 'mobile', 'design'],
  },
  {
    id: 'p3',
    name: 'Rohan Kumar',
    tagline: 'Video editor and motion graphics artist',
    skills: ['Video Editor', 'Motion Graphics Artist'],
    rateMin: 3000,
    rateMax: 9000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['film', 'content', 'animation'],
  },
  {
    id: 'p4',
    name: 'Anika Verma',
    tagline: 'Mobile app developer, React Native specialist',
    skills: ['React Native Developer', 'iOS Developer', 'Android Developer'],
    rateMin: 5000,
    rateMax: 13000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['mobile', 'web'],
  },
  {
    id: 'p5',
    name: 'James Wright',
    tagline: 'AI/ML engineer, deep learning expert',
    skills: ['Machine Learning Engineer', 'Data Scientist', 'AI Engineer'],
    rateMin: 7000,
    rateMax: 18000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['ai', 'data', 'web'],
  },
  {
    id: 'p6',
    name: 'Sophia Rodriguez',
    tagline: 'Content strategist and writer',
    skills: ['Content Writer', 'Copywriter', 'Content Strategist'],
    rateMin: 2500,
    rateMax: 7000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['content', 'marketing', 'writing'],
  },
  {
    id: 'p7',
    name: 'David Park',
    tagline: 'DevOps engineer, cloud infrastructure specialist',
    skills: ['DevOps Engineer', 'Cloud Architect', 'Infrastructure Engineer'],
    rateMin: 6000,
    rateMax: 15000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['cloud', 'devops', 'web'],
  },
  {
    id: 'p8',
    name: 'Emma Thompson',
    tagline: 'Graphic designer and illustrator',
    skills: ['Graphic Designer', 'Illustrator', 'Brand Designer'],
    rateMin: 3000,
    rateMax: 8500,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['design', 'animation', 'content'],
  },
  {
    id: 'p9',
    name: 'Carlos Santos',
    tagline: 'Game developer, Unity expert',
    skills: ['Game Developer', 'Unity Developer', '3D Programmer'],
    rateMin: 5500,
    rateMax: 14000,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['game', 'web', 'animation'],
  },
  {
    id: 'p10',
    name: 'Lisa Johnson',
    tagline: 'QA Engineer, automation specialist',
    skills: ['QA Engineer', 'Test Automation', 'QA Lead'],
    rateMin: 3500,
    rateMax: 9500,
    currency: 'USD',
    availableForInvites: true,
    categoryIds: ['web', 'mobile', 'game'],
  },
];
