export interface IndianCity {
  city: string;
  state: string;
}

export const INDIAN_CITIES: IndianCity[] = [
  // Metros
  { city: 'Hyderabad',       state: 'Telangana' },
  { city: 'Bengaluru',       state: 'Karnataka' },
  { city: 'Mumbai',          state: 'Maharashtra' },
  { city: 'Delhi',           state: 'Delhi' },
  { city: 'Chennai',         state: 'Tamil Nadu' },
  { city: 'Kolkata',         state: 'West Bengal' },
  { city: 'Pune',            state: 'Maharashtra' },
  { city: 'Ahmedabad',       state: 'Gujarat' },
  // Tier 2
  { city: 'Jaipur',          state: 'Rajasthan' },
  { city: 'Surat',           state: 'Gujarat' },
  { city: 'Lucknow',         state: 'Uttar Pradesh' },
  { city: 'Kanpur',          state: 'Uttar Pradesh' },
  { city: 'Nagpur',          state: 'Maharashtra' },
  { city: 'Indore',          state: 'Madhya Pradesh' },
  { city: 'Visakhapatnam',   state: 'Andhra Pradesh' },
  { city: 'Bhopal',          state: 'Madhya Pradesh' },
  { city: 'Patna',           state: 'Bihar' },
  { city: 'Vadodara',        state: 'Gujarat' },
  { city: 'Thane',           state: 'Maharashtra' },
  { city: 'Coimbatore',      state: 'Tamil Nadu' },
  { city: 'Agra',            state: 'Uttar Pradesh' },
  { city: 'Nashik',          state: 'Maharashtra' },
  { city: 'Faridabad',       state: 'Haryana' },
  { city: 'Meerut',          state: 'Uttar Pradesh' },
  { city: 'Rajkot',          state: 'Gujarat' },
  { city: 'Varanasi',        state: 'Uttar Pradesh' },
  { city: 'Srinagar',        state: 'Jammu & Kashmir' },
  { city: 'Aurangabad',      state: 'Maharashtra' },
  { city: 'Dhanbad',         state: 'Jharkhand' },
  { city: 'Amritsar',        state: 'Punjab' },
  { city: 'Allahabad',       state: 'Uttar Pradesh' },
  { city: 'Ranchi',          state: 'Jharkhand' },
  { city: 'Howrah',          state: 'West Bengal' },
  { city: 'Jabalpur',        state: 'Madhya Pradesh' },
  { city: 'Gwalior',         state: 'Madhya Pradesh' },
  { city: 'Vijayawada',      state: 'Andhra Pradesh' },
  { city: 'Jodhpur',         state: 'Rajasthan' },
  { city: 'Madurai',         state: 'Tamil Nadu' },
  { city: 'Raipur',          state: 'Chhattisgarh' },
  { city: 'Kota',            state: 'Rajasthan' },
  { city: 'Guwahati',        state: 'Assam' },
  { city: 'Chandigarh',      state: 'Chandigarh' },
  { city: 'Solapur',         state: 'Maharashtra' },
  { city: 'Hubli-Dharwad',   state: 'Karnataka' },
  { city: 'Bareilly',        state: 'Uttar Pradesh' },
  { city: 'Moradabad',       state: 'Uttar Pradesh' },
  { city: 'Mysuru',          state: 'Karnataka' },
  { city: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { city: 'Tiruppur',        state: 'Tamil Nadu' },
  { city: 'Salem',           state: 'Tamil Nadu' },
  { city: 'Warangal',        state: 'Telangana' },
  { city: 'Guntur',          state: 'Andhra Pradesh' },
  { city: 'Nellore',         state: 'Andhra Pradesh' },
  { city: 'Kochi',           state: 'Kerala' },
  { city: 'Thiruvananthapuram', state: 'Kerala' },
  { city: 'Kozhikode',       state: 'Kerala' },
  { city: 'Bhubaneswar',     state: 'Odisha' },
  { city: 'Cuttack',         state: 'Odisha' },
  { city: 'Dehradun',        state: 'Uttarakhand' },
  { city: 'Shimla',          state: 'Himachal Pradesh' },
  { city: 'Jammu',           state: 'Jammu & Kashmir' },
  { city: 'Noida',           state: 'Uttar Pradesh' },
  { city: 'Gurugram',        state: 'Haryana' },
  { city: 'Navi Mumbai',     state: 'Maharashtra' },
  { city: 'Secunderabad',    state: 'Telangana' },
];
