/** Demo seed identifiers — keep in sync with lib/demoData.ts and backend/utils/demoData.js */

export const DEMO_CONTACT_PATTERN = /@demo\.makebig\.in$/i;

export const DEMO_CONTACTS = [
  'priya@demo.makebig.in',
  'arjun@demo.makebig.in',
  'sneha@demo.makebig.in',
  'rahul@demo.makebig.in',
  'kavya@demo.makebig.in',
  'vikram@demo.makebig.in',
  'ananya@demo.makebig.in',
  'rohan@demo.makebig.in',
  'meera@demo.makebig.in',
  'aditya@demo.makebig.in',
];

export const DEMO_PROJECT_SLUGS = [
  'studysync-web-portal-hyderabad',
  'campusride-mobile-bangalore',
  'ai-study-buddy-pune',
  'brandkit-design-system-mumbai',
  'healthtrack-campus-chennai',
  'pixelquest-game-delhi',
  'growthlaunch-marketing-hub-hyderabad',
  'datadash-analytics-bangalore',
  'shortfilm-collab-kochi',
  'cloudcamp-devops-kit-hyderabad',
];

export function isDemoContact(contact) {
  return DEMO_CONTACT_PATTERN.test(String(contact || '').trim());
}

export function isDemoProject(project) {
  const slug = String(project?.slug || '').trim();
  const owner = String(project?.ownerContact || '').trim();
  if (DEMO_PROJECT_SLUGS.includes(slug)) return true;
  if (isDemoContact(owner)) return true;
  return false;
}

/** Full demo users with profile fields for seed-demo.mjs */
export const DEMO_USERS = [
  {
    name: 'Priya Sharma',
    contact: 'priya@demo.makebig.in',
    college: 'CMR Institute of Technology, Hyderabad',
    graduationYear: '2026',
    city: 'Hyderabad',
    state: 'Telangana',
    skills: ['frontend developer', 'react', 'typescript', 'ui/ux designer'],
    hobbies: ['Hackathons', 'Open source'],
    profile: {
      role: 'creator',
      tagline: 'Full-stack builder · Web products for campus teams',
      bio: 'Final-year CSE student building StudySync and mentoring juniors on React. Looking for backend teammates who ship weekly.',
      categoryIds: ['web'],
      portfolio: 'https://github.com/demo-priya\nhttps://linkedin.com/in/demo-priya',
      availableForInvites: true,
      rateMin: 8000,
      rateMax: 18000,
      currency: 'INR',
    },
  },
  {
    name: 'Arjun Reddy',
    contact: 'arjun@demo.makebig.in',
    college: 'RV College of Engineering, Bangalore',
    graduationYear: '2025',
    city: 'Bangalore',
    state: 'Karnataka',
    skills: ['android developer', 'react native developer', 'firebase'],
    hobbies: ['Mobile UX', 'Cricket'],
    profile: {
      role: 'creator',
      tagline: 'Mobile engineer · Flutter & React Native',
      bio: 'Built two campus apps with 500+ downloads. CampusRide is my latest — live tracking for shared rides.',
      categoryIds: ['mobile'],
      portfolio: 'https://github.com/demo-arjun',
      availableForInvites: true,
      rateMin: 10000,
      rateMax: 20000,
      currency: 'INR',
    },
  },
  {
    name: 'Sneha Patel',
    contact: 'sneha@demo.makebig.in',
    college: 'MIT World Peace University, Pune',
    graduationYear: '2026',
    city: 'Pune',
    state: 'Maharashtra',
    skills: ['ml engineer', 'llm application developer', 'python'],
    hobbies: ['Kaggle', 'Reading papers'],
    profile: {
      role: 'both',
      tagline: 'AI/ML · LLM apps for student productivity',
      bio: 'Shipped AI Study Buddy with Groq + RAG over lecture notes. Happy to pair with designers on AI UX.',
      categoryIds: ['ai'],
      portfolio: 'https://github.com/demo-sneha',
      availableForInvites: true,
      rateMin: 12000,
      rateMax: 22000,
      currency: 'INR',
    },
  },
  {
    name: 'Rahul Kumar',
    contact: 'rahul@demo.makebig.in',
    college: 'NMIMS Mumbai',
    graduationYear: '2025',
    city: 'Mumbai',
    state: 'Maharashtra',
    skills: ['ui/ux designer', 'product designer', 'figma'],
    hobbies: ['Design systems', 'Photography'],
    profile: {
      role: 'creator',
      tagline: 'Product designer · Design systems & brand',
      bio: 'BrandKit maintainer. I help early teams get from wireframe to polished UI in two sprints.',
      categoryIds: ['design'],
      portfolio: 'https://behance.net/demo-rahul',
      availableForInvites: true,
      rateMin: 6000,
      rateMax: 15000,
      currency: 'INR',
    },
  },
  {
    name: 'Kavya Menon',
    contact: 'kavya@demo.makebig.in',
    college: 'SRM Institute, Chennai',
    graduationYear: '2026',
    city: 'Chennai',
    state: 'Tamil Nadu',
    skills: ['full stack developer', 'healthtech', 'mongodb'],
    hobbies: ['Public health', 'Yoga'],
    profile: {
      role: 'creator',
      tagline: 'Healthtech builder · Campus wellness products',
      bio: 'HealthTrack helps students log sleep, steps, and mental-health check-ins. Prior intern at a health startup.',
      categoryIds: ['health'],
      portfolio: 'https://github.com/demo-kavya',
      availableForInvites: true,
      rateMin: 0,
      rateMax: 12000,
      currency: 'INR',
    },
  },
  {
    name: 'Vikram Singh',
    contact: 'vikram@demo.makebig.in',
    college: 'DTU Delhi',
    graduationYear: '2025',
    city: 'Delhi',
    state: 'Delhi',
    skills: ['unity / unreal developer', 'game designer', '3d artist'],
    hobbies: ['Indie games', 'Chess'],
    profile: {
      role: 'creator',
      tagline: 'Game dev · Unity & multiplayer prototypes',
      bio: 'PixelQuest is a co-op puzzle platformer for college game jams. Looking for sound designers.',
      categoryIds: ['game'],
      portfolio: 'https://itch.io/demo-vikram',
      availableForInvites: true,
      rateMin: 5000,
      rateMax: 14000,
      currency: 'INR',
    },
  },
  {
    name: 'Ananya Rao',
    contact: 'ananya@demo.makebig.in',
    college: 'Osmania University, Hyderabad',
    graduationYear: '2026',
    city: 'Hyderabad',
    state: 'Telangana',
    skills: ['growth marketer', 'seo specialist', 'content creator'],
    hobbies: ['LinkedIn growth', 'Podcasts'],
    profile: {
      role: 'both',
      tagline: 'Growth & content · Student startup launches',
      bio: 'Helped 4 campus teams get their first 100 users. GrowthLaunch is our shared playbook + templates.',
      categoryIds: ['marketing'],
      portfolio: 'https://linkedin.com/in/demo-ananya',
      availableForInvites: true,
      rateMin: 4000,
      rateMax: 10000,
      currency: 'INR',
    },
  },
  {
    name: 'Rohan Das',
    contact: 'rohan@demo.makebig.in',
    college: 'PES University, Bangalore',
    graduationYear: '2025',
    city: 'Bangalore',
    state: 'Karnataka',
    skills: ['data scientist', 'data analyst', 'python'],
    hobbies: ['Data viz', 'Table tennis'],
    profile: {
      role: 'creator',
      tagline: 'Data science · Dashboards for student teams',
      bio: 'DataDash turns project metrics into weekly insight decks. Previously analytics lead for a college fest.',
      categoryIds: ['data'],
      portfolio: 'https://github.com/demo-rohan',
      availableForInvites: true,
      rateMin: 8000,
      rateMax: 16000,
      currency: 'INR',
    },
  },
  {
    name: 'Meera Nair',
    contact: 'meera@demo.makebig.in',
    college: 'CUSAT Kochi',
    graduationYear: '2026',
    city: 'Kochi',
    state: 'Kerala',
    skills: ['director', 'video editor', 'cinematographer'],
    hobbies: ['Short films', 'Travel'],
    profile: {
      role: 'creator',
      tagline: 'Filmmaker · Short-form & documentary',
      bio: 'ShortFilm Collab connects writers, DPs, and editors for 48-hour film challenges across Kerala colleges.',
      categoryIds: ['film'],
      portfolio: 'https://vimeo.com/demo-meera',
      availableForInvites: true,
      rateMin: 3000,
      rateMax: 12000,
      currency: 'INR',
    },
  },
  {
    name: 'Aditya Choudhary',
    contact: 'aditya@demo.makebig.in',
    college: 'CMR Institute of Technology, Hyderabad',
    graduationYear: '2025',
    city: 'Hyderabad',
    state: 'Telangana',
    skills: ['devops engineer', 'cloud architect', 'aws / azure / gcp engineer'],
    hobbies: ['Kubernetes', 'Tech talks'],
    profile: {
      role: 'creator',
      tagline: 'DevOps · CI/CD for student product teams',
      bio: 'CloudCamp ships Terraform templates + GitHub Actions so college teams deploy without breaking prod.',
      categoryIds: ['cloud', 'devops'],
      portfolio: 'https://github.com/demo-aditya',
      availableForInvites: true,
      rateMin: 10000,
      rateMax: 24000,
      currency: 'INR',
    },
  },
];

export const DEMO_PROJECTS = [
  {
    name: 'StudySync Web Portal',
    slug: 'studysync-web-portal-hyderabad',
    desc: 'Shared workspace for college project teams — tasks, files, and standups in one place. Built for final-year groups who live in WhatsApp chaos.',
    categoryId: 'web',
    projectPurpose: 'college',
    roles: ['Frontend Developer', 'Backend Developer', 'UI/UX Designer'],
    ownerContact: 'priya@demo.makebig.in',
    city: 'Hyderabad',
    state: 'Telangana',
    currency: 'INR',
    salaryMin: 8000,
    salaryMax: 18000,
    journeyStage: 'mvp',
    demoDayReady: false,
    team: [
      { contact: 'priya@demo.makebig.in', role: 'owner' },
      { contact: 'arjun@demo.makebig.in', role: 'Frontend Developer' },
      { contact: 'aditya@demo.makebig.in', role: 'DevOps Engineer' },
    ],
    posts: [{ author: 'priya@demo.makebig.in', body: 'StudySync beta is live for 3 CMRIT teams — task board + weekly standups shipped.' }],
    tasks: [
      { title: 'Launch landing page', status: 'done', priority: 'high', assignee: 'priya@demo.makebig.in' },
      { title: 'Invite 5 pilot teams', status: 'in-progress', priority: 'medium', assignee: 'priya@demo.makebig.in' },
    ],
  },
  {
    name: 'CampusRide Mobile App',
    slug: 'campusride-mobile-bangalore',
    desc: 'Carpool and bike-pool matching for campus commutes with live ETA and split fare.',
    categoryId: 'mobile',
    projectPurpose: 'college',
    roles: ['React Native Developer', 'Android Developer', 'UI Designer'],
    ownerContact: 'arjun@demo.makebig.in',
    city: 'Bangalore',
    state: 'Karnataka',
    currency: 'INR',
    salaryMin: 10000,
    salaryMax: 20000,
    journeyStage: 'beta',
    demoDayReady: true,
    demoDayPitch: 'Live carpool matching for 3 Bangalore campuses — 40 beta testers this week.',
    team: [
      { contact: 'arjun@demo.makebig.in', role: 'owner' },
      { contact: 'rahul@demo.makebig.in', role: 'UI Designer' },
      { contact: 'rohan@demo.makebig.in', role: 'Backend Developer' },
    ],
    posts: [{ author: 'arjun@demo.makebig.in', body: 'Android build on Play internal track — 40 beta testers this week.' }],
    tasks: [
      { title: 'Map integration', status: 'done', priority: 'high', assignee: 'arjun@demo.makebig.in' },
      { title: 'Payment split flow', status: 'todo', priority: 'high', assignee: 'arjun@demo.makebig.in' },
    ],
  },
  {
    name: 'AI Study Buddy',
    slug: 'ai-study-buddy-pune',
    desc: 'LLM tutor that reads your syllabus PDFs and quizzes you before exams. Privacy-first — notes stay on your project workspace.',
    categoryId: 'ai',
    projectPurpose: 'education',
    roles: ['ML Engineer', 'LLM Application Developer', 'Backend Developer'],
    ownerContact: 'sneha@demo.makebig.in',
    city: 'Pune',
    state: 'Maharashtra',
    currency: 'INR',
    salaryMin: 12000,
    salaryMax: 22000,
    journeyStage: 'prototype',
    demoDayReady: false,
    team: [
      { contact: 'sneha@demo.makebig.in', role: 'owner' },
      { contact: 'priya@demo.makebig.in', role: 'Frontend Developer' },
    ],
    posts: [{ author: 'sneha@demo.makebig.in', body: 'RAG pipeline v2 — 92% accuracy on sample MCQ bank from OS notes.' }],
    tasks: [
      { title: 'Embed lecture PDFs', status: 'done', priority: 'high', assignee: 'sneha@demo.makebig.in' },
      { title: 'Add quiz mode UI', status: 'in-progress', priority: 'medium', assignee: 'sneha@demo.makebig.in' },
    ],
  },
  {
    name: 'BrandKit Design System',
    slug: 'brandkit-design-system-mumbai',
    desc: 'Figma component library + tokens for student startups — ship consistent UI without hiring a senior designer.',
    categoryId: 'design',
    projectPurpose: 'employment',
    roles: ['UI/UX Designer', 'Product Designer', 'Frontend Developer'],
    ownerContact: 'rahul@demo.makebig.in',
    city: 'Mumbai',
    state: 'Maharashtra',
    currency: 'INR',
    salaryMin: 6000,
    salaryMax: 15000,
    journeyStage: 'launch',
    demoDayReady: true,
    demoDayPitch: '40-component Figma kit used by 8 student startups — design handoff in under 48 hours.',
    team: [
      { contact: 'rahul@demo.makebig.in', role: 'owner' },
      { contact: 'ananya@demo.makebig.in', role: 'Brand Strategist' },
    ],
    posts: [{ author: 'rahul@demo.makebig.in', body: 'Published 40 components + dark mode tokens — free for college teams.' }],
    tasks: [
      { title: 'Button & form kit', status: 'done', priority: 'high', assignee: 'rahul@demo.makebig.in' },
      { title: 'Marketing page templates', status: 'todo', priority: 'low', assignee: 'rahul@demo.makebig.in' },
    ],
  },
  {
    name: 'HealthTrack Campus',
    slug: 'healthtrack-campus-chennai',
    desc: 'Wellness tracker for hostels — sleep, hydration, mood check-ins, and anonymous counselor booking.',
    categoryId: 'health',
    projectPurpose: 'community',
    roles: ['Full Stack Developer', 'UI/UX Designer', 'Outreach Lead'],
    ownerContact: 'kavya@demo.makebig.in',
    city: 'Chennai',
    state: 'Tamil Nadu',
    currency: 'INR',
    salaryMin: 0,
    salaryMax: 12000,
    journeyStage: 'mvp',
    demoDayReady: false,
    team: [
      { contact: 'kavya@demo.makebig.in', role: 'owner' },
      { contact: 'meera@demo.makebig.in', role: 'Outreach Lead' },
      { contact: 'vikram@demo.makebig.in', role: 'Full Stack Developer' },
    ],
    posts: [{ author: 'kavya@demo.makebig.in', body: 'Pilot with 2 hostels — 200 daily active check-ins.' }],
    tasks: [
      { title: 'Mood survey flow', status: 'done', priority: 'high', assignee: 'kavya@demo.makebig.in' },
      { title: 'Counselor calendar', status: 'in-progress', priority: 'high', assignee: 'kavya@demo.makebig.in' },
    ],
  },
  {
    name: 'PixelQuest Game',
    slug: 'pixelquest-game-delhi',
    desc: 'Co-op puzzle platformer for 2–4 players — built for college game jams and Steam demo day.',
    categoryId: 'game',
    projectPurpose: 'college',
    roles: ['Unity / Unreal Developer', 'Game Designer', '3D Artist'],
    ownerContact: 'vikram@demo.makebig.in',
    city: 'Delhi',
    state: 'Delhi',
    currency: 'INR',
    salaryMin: 5000,
    salaryMax: 14000,
    journeyStage: 'beta',
    demoDayReady: true,
    demoDayPitch: 'Co-op puzzle platformer — multiplayer lobby + 3 levels playable for Steam Next Fest.',
    team: [
      { contact: 'vikram@demo.makebig.in', role: 'owner' },
      { contact: 'meera@demo.makebig.in', role: 'Video Editor' },
    ],
    posts: [{ author: 'vikram@demo.makebig.in', body: 'Level 3 boss fight playable — need sound designer for final polish.' }],
    tasks: [
      { title: 'Multiplayer lobby', status: 'done', priority: 'high', assignee: 'vikram@demo.makebig.in' },
      { title: 'Boss encounter', status: 'in-progress', priority: 'high', assignee: 'vikram@demo.makebig.in' },
    ],
  },
  {
    name: 'GrowthLaunch Marketing Hub',
    slug: 'growthlaunch-marketing-hub-hyderabad',
    desc: 'Templates, calendars, and analytics for student founders launching on Instagram and LinkedIn.',
    categoryId: 'marketing',
    projectPurpose: 'employment',
    roles: ['Growth Marketer', 'Content Creator', 'SEO Specialist'],
    ownerContact: 'ananya@demo.makebig.in',
    city: 'Hyderabad',
    state: 'Telangana',
    currency: 'INR',
    salaryMin: 4000,
    salaryMax: 10000,
    journeyStage: 'research',
    demoDayReady: false,
    team: [
      { contact: 'ananya@demo.makebig.in', role: 'owner' },
      { contact: 'sneha@demo.makebig.in', role: 'Content Creator' },
    ],
    posts: [{ author: 'ananya@demo.makebig.in', body: 'Launch playbook v1 — 30-day content calendar for campus apps.' }],
    tasks: [
      { title: 'Notion template pack', status: 'done', priority: 'medium', assignee: 'ananya@demo.makebig.in' },
      { title: 'Case study: 3 teams', status: 'todo', priority: 'medium', assignee: 'ananya@demo.makebig.in' },
    ],
  },
  {
    name: 'DataDash Analytics',
    slug: 'datadash-analytics-bangalore',
    desc: 'Plug-and-play dashboards for student startups — track signups, retention, and weekly ship velocity.',
    categoryId: 'data',
    projectPurpose: 'employment',
    roles: ['Data Scientist', 'Data Analyst', 'Backend Developer'],
    ownerContact: 'rohan@demo.makebig.in',
    city: 'Bangalore',
    state: 'Karnataka',
    currency: 'INR',
    salaryMin: 8000,
    salaryMax: 16000,
    journeyStage: 'mvp',
    demoDayReady: false,
    team: [
      { contact: 'rohan@demo.makebig.in', role: 'owner' },
      { contact: 'aditya@demo.makebig.in', role: 'Platform Engineer' },
    ],
    posts: [{ author: 'rohan@demo.makebig.in', body: 'Connected Mongo + CSV import — first dashboard live in 15 minutes.' }],
    tasks: [
      { title: 'CSV ingest pipeline', status: 'done', priority: 'high', assignee: 'rohan@demo.makebig.in' },
      { title: 'Retention cohort chart', status: 'in-progress', priority: 'medium', assignee: 'rohan@demo.makebig.in' },
    ],
  },
  {
    name: 'ShortFilm Collab Studio',
    slug: 'shortfilm-collab-kochi',
    desc: 'Match writers, DPs, and editors for 48-hour film challenges across Kerala colleges.',
    categoryId: 'film',
    projectPurpose: 'community',
    roles: ['Director', 'Video Editor', 'Cinematographer'],
    ownerContact: 'meera@demo.makebig.in',
    city: 'Kochi',
    state: 'Kerala',
    currency: 'INR',
    salaryMin: 3000,
    salaryMax: 12000,
    journeyStage: 'launch',
    demoDayReady: true,
    demoDayPitch: '48-hour film collab network — first short screened at CUSAT fest with 12 credited teammates.',
    team: [
      { contact: 'meera@demo.makebig.in', role: 'owner' },
      { contact: 'rahul@demo.makebig.in', role: 'Product Designer' },
      { contact: 'kavya@demo.makebig.in', role: 'Director' },
    ],
    posts: [{ author: 'meera@demo.makebig.in', body: 'First collab film screened at CUSAT fest — 12 team members credited.' }],
    tasks: [
      { title: 'Crew matching flow', status: 'done', priority: 'high', assignee: 'meera@demo.makebig.in' },
      { title: 'Festival submission kit', status: 'todo', priority: 'low', assignee: 'meera@demo.makebig.in' },
    ],
  },
  {
    name: 'CloudCamp DevOps Kit',
    slug: 'cloudcamp-devops-kit-hyderabad',
    desc: 'Terraform + GitHub Actions templates so college teams deploy Next.js + Mongo without breaking prod.',
    categoryId: 'cloud',
    projectPurpose: 'education',
    roles: ['DevOps Engineer', 'Cloud Architect', 'Platform Engineer'],
    ownerContact: 'aditya@demo.makebig.in',
    city: 'Hyderabad',
    state: 'Telangana',
    currency: 'INR',
    salaryMin: 10000,
    salaryMax: 24000,
    journeyStage: 'beta',
    demoDayReady: false,
    team: [
      { contact: 'aditya@demo.makebig.in', role: 'owner' },
      { contact: 'priya@demo.makebig.in', role: 'Full Stack Developer' },
      { contact: 'arjun@demo.makebig.in', role: 'Mobile Developer' },
    ],
    posts: [{ author: 'aditya@demo.makebig.in', body: 'One-click Render + Vercel deploy script — tested on 5 Make Big teams.' }],
    tasks: [
      { title: 'Terraform modules', status: 'done', priority: 'high', assignee: 'aditya@demo.makebig.in' },
      { title: 'CI lint + test gate', status: 'in-progress', priority: 'medium', assignee: 'aditya@demo.makebig.in' },
    ],
  },
];
